#!perl

# DATE
# VERSION

use 5.010001;
use strict;
use warnings;

use Log::ger::Level::FromEnv;
use Log::ger::Output 'Screen';

require Perinci::Access::Simple::Server::Pipe;

Perinci::Access::Simple::Server::Pipe->new->run;

1;
#ABSTRACT: Default Riap::Simple server over pipe
#PODNAME:

=head1 SYNOPSIS

 # access the server
 % perl -MPerinci::Access -e'
     my $pa = Perinci::Access->new;
     my $res = $pa->request(call=>"riap+pipe:/path/to/peri-pipe////Foo/func",
                            {args=>{arg1=>1, arg2=>2}});'


=head1 SEE ALSO

L<Perinci::Access::Simple::Server::Pipe>

=cut
